### ISSUE TITLE
Cannot connect to MySQL from Azure JAVA Function

### ISSUE THREAD

**Issue by steccami** [Azure/azure-functions-java-worker#246]
Hi all,

I am developing a simple JAVA Time triggered Azure Function. I am trying to connect to a Azure MySQL instance but I keep getting this error: 

**[Information] com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.**

Here is the code:        
String url ="jdbc:mysql://XXXX.mysql.database.azure.com:3306/DBNAME?useSSL=true&requireSSL=false"; 
connect = DriverManager.getConnection(url, "user@DBNAME", "passwd");

statement = connect.createStatement()

resultSet = statement.executeQuery("select * from table1");

while (resultSet.next()) {
//App logic
}

I am using the following library: 

  
<dependency>
<groupId>mysql</groupId>
<artifactId>mysql-connector-java</artifactId>
<version>8.0.13</version>
</dependency>

Notes: 

- The program works fine on my local machine (i.e., after adding my IP address to the MySQL firewall, I can reach the DB from my machine);

- I've already tried different mysql libraries (8.0.13, 5.1.45, 5.1.42): nothing changes;

- Another Azure function implemented with NodeJS is able to reach the DB;

- I tried to add the Function "ADDITIONAL OUTBOUND IP ADDRESSES" to the MySQL firewall: nothing changes. 

- I developed a simple C# Azure function, it works well. It seems to be a problem strictly related to the JAVA-based Azure Function env.

- I also created a fat jar file as suggested here: https://github.com/Azure/azure-functions-java-worker/issues/35#issuecomment-345047272

Any ideas? 

Thank you in advance.

**Comment by marwaadihu** [comment]
Hello, I am just inserting some rows in the table using the same code and URL, I am facing the same issue :+1:

**Comment by sureddy1** [comment]
We are actively working to fix this issue. This is specific to the java version used with functions. 

Can you use this workaround for now: 

1) Upload a custom JRE (lets say JRE 1.8_0_202) to D:/home/site/jre1.8.0_202 and add these application settings for your function from portal:

Key: languageWorkers:java:defaultExecutablePath
Value: D:/home/site/jre1.8.0_202/bin/java

If you are using consumption plan, please add this app setting as well: 

Key: WEBSITE_USE_PLACEHOLDER
Value: 0

**Comment by fabiocav** [comment]
This is resolved with the release currently being deployed. Please use https://github.com/Azure/app-service-announcements/issues/188 to track the deployment progress.

**Comment by pragnagopa** [comment]
On AppService, JAVA_HOME  is set to D:\Program Files\Java\zulu8.31.0.2-jre8.0.181-win_x64 while the latest JRE on AppService is: D:\Program Files\Java\zulu8.36.0.1-jre8.0.202-win_x64.   Needs to be updated.

**Comment by pragnagopa** [comment]
Confirmed with customer issue is resolved. It works with both zulu8.31.0.2-jre8.0.181-win_x64  and zulu8.36.0.1-jre8.0.202-win_x64.

**Comment by joelw** [comment]
Is anyone else still having problems with this? I'm using runtime 2.0.12673.0 and have tried the default Java, zulu8.40.0.25-ca-jre8.0.222-win_i686, and jre1.8.0_191 (which worked on a different Functions App, but not a second one) without any success.
