### ISSUE TITLE
Error when passing a byte array larger than 4MB

### ISSUE THREAD

**Issue by paramount-jay** [Azure/azure-functions-java-worker#70]
When the Azure function contains a `byte[]` input parameter larger than 4MB the following error is thrown on the server side:
` java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: io.grpc.netty.NettyClientTransport$3: Frame size XXX exceeds maximum: 4194304.`

4MB is quite limiting when processing files for instance.
It should be possible to change the maximum message size in the gRPC by using a method parameter attribute or more globally.

**Comment by kevinhillinger** [comment]
Upon investigation, there's an open issue with grpc on this. Ref: [grpc/grpc-java/#3996](https://github.com/grpc/grpc-java/issues/3996)

In [JavaWorkerClient.java](azure-functions-java-worker/azure-functions-java-worker/src/main/java/com/microsoft/azure/webjobs/script/JavaWorkerClient.java) when defining the channel with the builder, a max inbound message size, e.g. `maxInboundMessageSize(max)` can be set as follows:

```java
this.channel = ManagedChannelBuilder.forAddress(app.getHost(), app.getPort())
.usePlaintext(true)
.maxInboundMessageSize(max).build();
```

A discussion should be had about the max file size that Functions may support.

**Comment by JunyiYi** [comment]
@pragnagopa , how about other languages and host? Do you have any comments on the maximum binary size?

**Comment by pragnagopa** [comment]
This is a known limitation in the host. We are tracking it here [Azure/azure-functions-host/issues/2301](https://github.com/Azure/azure-functions-host/issues/2301).

**Comment by kevinhillinger** [comment]
@pragnagopa @JunyiYi based on my understanding, this requires a code change for both codebases. The channel builder in Java must specify the inbound message size max.

I've commented on the host change requirement in [Azure/azure-functions-host/issues/2301](https://github.com/Azure/azure-functions-host/issues/2301)

**Comment by pragnagopa** [comment]
Fixed in Commit # [e6c21f8c0d825fd7397d84e42fecd911a14061b1](https://github.com/Azure/azure-functions-java-worker/commit/e6c21f8c0d825fd7397d84e42fecd911a14061b1)

**Comment by SilicusShraddha** [comment]
Hi,

I was facing the issue issue while uploading a file of 17MB through azure functions. But, the latest jar of azure-functions-java-worker 1.0.0-beta-4 , is still not available at maven repo. So , i externally added this jar in the maven build path. Now, I am not facing StatusRuntimeException.

But, using latest jar, now i am not even able to upload a file having size in KB, though the same function which was working earlier. Earlier it was taking 3 second to upload, Now i am getting
 
"[Error] Microsoft.Azure.WebJobs.Host: Timeout value of 00:05:00 was exceeded by function: Functions.hello."

"The specified CGI application encountered an error and the server terminated the process".

Is this bcoz of the latest hotfix? I tried with both the latest and old version of the jar. But function is not at all responding now. It is unstable?

**Comment by pragnagopa** [comment]
@SilicusShraddha - We have identified an issue with the tooling:
For existing Java functions, that were deployed using [Maven Plugin version 0.2.1 ](https://mvnrepository.com/artifact/com.microsoft.azure/azure-functions-maven-plugin/0.2.1)or any other earlier versions will be affected as the deployment includes package azure-functions-java-core 1.0.0-beta-2 that is incompatible with the current functions runtime 2.0.11737

An update to maven plugin will be published soon. Until then please follow workarounds mentioned below to avoid downtime:

Can you please delete azure-functions-java-core-1.0.0-beta-2.jar from the lib folder and let us know if your are unblocked?

Please note that azure-functions-java-core-1.0.0-beta-2.jar needs to be deleted from the lib folder for new Java functions as well until we release updated maven plugin.

**Comment by pragnagopa** [comment]
Also, please note that azure-functions-java-worker 1.0.0-beta-4 will not be published to maven.

**Comment by SilicusShraddha** [comment]
Hi,

I tried the workarounds you suggested, but none worked.

Even simplest Azure functions with java (simple printing "hello world") are failing to respond. More than five minutes. Its not about file uploading. Its all over simple functions as well. After 5-6 successfull attempts, i get RESOURCE_EXHAUSTED and then, as you said, deleting azure-functions-java-core-1.0.0-beta-2.jar from lib folder helps resolving RESOURCE_EXHAUSTED issues, but then the function just soeant respond at all. It gives 

**************"System.Private.CoreLib: One or more errors occurred. (Worker process with pid xxxx exited with code 1)"****************

Please help.
